const CartData = [
  {
    title: "White turtle shirt",
    id: 1,
    image: "c1.jpg",
    quantity: 1,
    price: 19.99,
    category: "Casual",
  },
  {
    title: "Denim jacket",
    id: 2,
    image: "c2.jpg",
    quantity: 1,
    price: 29.99,
    category: "Casual",
  },
  {
    title: "Hooded Sweatshirt",
    id: 3,
    image: "c3.jpg",
    quantity: 1,
    price: 39.99,
    category: "Casual",
  },
  {
    title: "Plaid Shirt",
    id: 4,
    image: "c4.jpg",
    quantity: 1,
    price: 24.99,
    category: "Casual",
  },
  {
    title: "Chino Pants",
    id: 5,
    image: "c5.jpg",
    quantity: 1,
    price: 34.99,
    category: "Casual",
  },
  {
    title: "Layer Shirt",
    id: 6,
    image: "c6.jpg",
    quantity: 1,
    price: 22.99,
    category: "Casual",
  },
  {
    title: "Funky Wear",
    id: 7,
    image: "c7.jpg",
    quantity: 1,
    price: 27.99,
    category: "Casual",
  },
  {
    title: "Casual Blazer",
    id: 8,
    image: "c8.jpg",
    quantity: 1,
    price: 49.99,
    category: "Casual",
  },
  {
    title: "Skinny jeans",
    id: 9,
    image: "c9.jpg",
    quantity: 1,
    price: 39.99,
    category: "Casual",
  },
  {
    title: "White T-shirt",
    id: 10,
    image: "c10.jpg",
    quantity: 1,
    price: 29.99,
    category: "Casual",
  },
  {
    title: "black jacket",
    id: 11,
    image: "c11.jpg",
    quantity: 1,
    price: 26.99,
    category: "Casual",
  },
  {
    title: "Linen Shirt",
    id: 12,
    image: "c12.jpg",
    quantity: 1,
    price: 32.99,
    category: "Casual",
  },
  {
    title: "white short",
    id: 13,
    image: "c13.jpg",
    quantity: 1,
    price: 21.99,
    category: "Casual",
  },
  {
    title: "Jumpsuit",
    id: 14,
    image: "c14.jpg",
    quantity: 1,
    price: 44.99,
    category: "Casual",
  },
  {
    title: "pink skit",
    id: 15,
    image: "c15.jpg",
    quantity: 1,
    price: 37.99,
    category: "Casual",
  },
  {
    title: "Cropped Jeans",
    id: 16,
    image: "c16.jpg",
    quantity: 1,
    price: 31.99,
    category: "Casual",
  },
  {
    title: "Twin dress",
    id: 17,
    image: "c17.jpg",
    quantity: 1,
    price: 28.99,
    category: "Casual",
  },
  {
    title: "Blue short",
    id: 18,
    image: "c18.jpg",
    quantity: 1,
    price: 23.99,
    category: "Casual",
  },
  {
    title: "blazer with short",
    id: 19,
    image: "c19.jpg",
    quantity: 1,
    price: 36.99,
    category: "Casual",
  },
  {
    title: "blue jacket",
    id: 20,
    image: "c20.jpg",
    quantity: 1,
    price: 41.99,
    category: "Casual",
  },
  {
    title: "Blue skits",
    id: 21,
    image: "e1.jpg",
    quantity: 1,
    price: 79.99,
    category: "Elegant",
  },
  {
    title: "Elegant Blazer",
    id: 22,
    image: "e2.jpg",
    quantity: 1,
    price: 89.99,
    category: "Elegant",
  },
  {
    title: "Elegant Tuxedo",
    id: 23,
    image: "e3.jpg",
    quantity: 1,
    price: 129.99,
    category: "Elegant",
  },
  {
    title: "Elegant wear",
    id: 24,
    image: "e4.jpg",
    quantity: 1,
    price: 159.99,
    category: "Elegant",
  },
  {
    title: "Elegant black Suit",
    id: 25,
    image: "e5.jpg",
    quantity: 1,
    price: 119.99,
    category: "Elegant",
  },
  {
    title: "Elegant Evening dress",
    id: 26,
    image: "e6.jpg",
    quantity: 1,
    price: 99.99,
    category: "Elegant",
  },
  {
    title: "Elegant Cocktail Dress",
    id: 27,
    image: "e7.jpg",
    quantity: 1,
    price: 109.99,
    category: "Elegant",
  },
  {
    title: "Elegant purple dress",
    id: 28,
    image: "e8.jpg",
    quantity: 1,
    price: 139.99,
    category: "Elegant",
  },
  {
    title: "Elegant white dress",
    id: 29,
    image: "e9.jpg",
    quantity: 1,
    price: 149.99,
    category: "Elegant",
  },
  {
    title: "Elegant blue jeans",
    id: 30,
    image: "e10.jpg",
    quantity: 1,
    price: 99.99,
    category: "Elegant",
  },
  {
    title: "Elegant yellow dress",
    id: 31,
    image: "e11.jpg",
    quantity: 1,
    price: 119.99,
    category: "Elegant",
  },
  {
    title: "Elegant pink dress",
    id: 32,
    image: "e12.jpg",
    quantity: 1,
    price: 129.99,
    category: "Elegant",
  },
  {
    title: "Elegant purple dress",
    id: 33,
    image: "e13.jpg",
    quantity: 1,
    price: 89.99,
    category: "Elegant",
  },
  {
    title: "Elegant wedding dress",
    id: 34,
    image: "e14.jpg",
    quantity: 1,
    price: 109.99,
    category: "Elegant",
  },
  {
    title: "Elegant black dress",
    id: 35,
    image: "e15.jpg",
    quantity: 1,
    price: 29.99,
    category: "Elegant",
  },
  {
    title: "Elegant pink dress",
    id: 36,
    image: "e16.jpg",
    quantity: 1,
    price: 39.99,
    category: "Elegant",
  },
  {
    title: "Elegant red dress",
    id: 37,
    image: "e17.jpg",
    quantity: 1,
    price: 49.99,
    category: "Elegant",
  },
  {
    title: "Elegant golden dress",
    id: 38,
    image: "e18.jpg",
    quantity: 1,
    price: 59.99,
    category: "Elegant",
  },
  {
    title: "Elegant maroon dress",
    id: 39,
    image: "e19.jpg",
    quantity: 1,
    price: 69.99,
    category: "Elegant",
  },
  {
    title: "Elegant black dress",
    id: 40,
    image: "e20.jpg",
    quantity: 1,
    price: 79.99,
    category: "Elegant",
  },
  {
    title: "Rose hair rings",
    id: 41,
    image: "a1.jpg",
    quantity: 1,
    price: 19.99,
    category: "Accessories",
  },
  {
    title: "Neakless",
    id: 42,
    image: "a2.jpg",
    quantity: 1,
    price: 29.99,
    category: "Accessories",
  },
  {
    title: "Earings",
    id: 43,
    image: "a3.jpg",
    quantity: 1,
    price: 39.99,
    category: "Accessories",
  },
  {
    title: "pair Earings",
    id: 44,
    image: "a4.jpg",
    quantity: 1,
    price: 49.99,
    category: "Accessories",
  },
  {
    title: "pair Earings",
    id: 45,
    image: "a5.jpg",
    quantity: 1,
    price: 59.99,
    category: "Accessories",
  },
  {
    title: "Engagement ring",
    id: 46,
    image: "a6.jpg",
    quantity: 1,
    price: 69.99,
    category: "Accessories",
  },
  {
    title: "Earings",
    id: 47,
    image: "a7.jpg",
    quantity: 1,
    price: 79.99,
    category: "Accessories",
  },
  {
    title: "Flower nackless",
    id: 48,
    image: "a8.jpg",
    quantity: 1,
    price: 89.99,
    category: "Accessories",
  },
  {
    title: "Vintage clock",
    id: 49,
    image: "a9.jpg",
    quantity: 1,
    price: 99.99,
    category: "Accessories",
  },
  {
    title: "bracelet",
    id: 50,
    image: "a10.jpg",
    quantity: 1,
    price: 109.99,
    category: "Accessories",
  },
  {
    title: "Earing",
    id: 51,
    image: "a11.jpg",
    quantity: 1,
    price: 119.99,
    category: "Accessories",
  },
  {
    title: "Glasses",
    id: 52,
    image: "a12.jpg",
    quantity: 1,
    price: 129.99,
    category: "Accessories",
  },
  {
    title: "Jumkas",
    id: 53,
    image: "a13.jpg",
    quantity: 1,
    price: 139.99,
    category: "Accessories",
  },
  {
    title: "Hair statner",
    id: 54,
    image: "a14.jpg",
    quantity: 1,
    price: 149.99,
    category: "Accessories",
  },
  {
    title: "Rings",
    id: 55,
    image: "a15.jpg",
    quantity: 1,
    price: 159.99,
    category: "Accessories",
  },
  {
    title: "Earrings",
    id: 56,
    image: "a16.jpg",
    quantity: 1,
    price: 169.99,
    category: "Accessories",
  },
  {
    title: "Thug Chain",
    id: 57,
    image: "a17.jpg",
    quantity: 1,
    price: 179.99,
    category: "Accessories",
  },
  {
    title: "Bow tie",
    id: 58,
    image: "a18.jpg",
    quantity: 1,
    price: 189.99,
    category: "Accessories",
  },
  {
    title: "Freshness Soap",
    id: 59,
    image: "a19.jpg",
    quantity: 1,
    price: 199.99,
    category: "Accessories",
  },
  {
    title: "Gold chains",
    id: 60,
    image: "a20.jpg",
    quantity: 1,
    price: 209.99,
    category: "Accessories",
  },
  {
    title: "Orange converse",
    id: 61,
    image: "s1.jpg",
    quantity: 1,
    price: 59.99,
    category: "Shoes",
  },
  {
    title: "Jordan high orange",
    id: 62,
    image: "s2.jpg",
    quantity: 1,
    price: 69.99,
    category: "Shoes",
  },
  {
    title: "White shoes",
    id: 63,
    image: "s3.jpg",
    quantity: 1,
    price: 79.99,
    category: "Shoes",
  },
  {
    title: "Yeezy adidas",
    id: 64,
    image: "s4.jpg",
    quantity: 1,
    price: 89.99,
    category: "Shoes",
  },
  {
    title: "Brown office shoe",
    id: 65,
    image: "s5.jpg",
    quantity: 1,
    price: 99.99,
    category: "Shoes",
  },
  {
    title: "High sendal",
    id: 66,
    image: "s6.jpg",
    quantity: 1,
    price: 109.99,
    category: "Shoes",
  },
  {
    title: "Black boot",
    id: 67,
    image: "s7.jpg",
    quantity: 1,
    price: 119.99,
    category: "Shoes",
  },
  {
    title: "Red shoe",
    id: 68,
    image: "s8.jpg",
    quantity: 1,
    price: 129.99,
    category: "Shoes",
  },
  {
    title: "Puma runner",
    id: 69,
    image: "s9.jpg",
    quantity: 1,
    price: 139.99,
    category: "Shoes",
  },
  {
    title: "White sneker",
    id: 70,
    image: "s10.jpg",
    quantity: 1,
    price: 149.99,
    category: "Shoes",
  },
  {
    title: "Red boot",
    id: 71,
    image: "s11.jpg",
    quantity: 1,
    price: 159.99,
    category: "Shoes",
  },
  {
    title: "Sporty red shoe",
    id: 72,
    image: "s12.jpg",
    quantity: 1,
    price: 169.99,
    category: "Shoes",
  },
  {
    title: "hiking boots",
    id: 73,
    image: "s13.jpg",
    quantity: 1,
    price: 179.99,
    category: "Shoes",
  },
  {
    title: "silever punch",
    id: 74,
    image: "s14.jpg",
    quantity: 1,
    price: 189.99,
    category: "Shoes",
  },
  {
    title: "Sporty yellow Shoes",
    id: 75,
    image: "s15.jpg",
    quantity: 1,
    price: 199.99,
    category: "Shoes",
  },
  {
    title: "Nike runner",
    id: 76,
    image: "s16.jpg",
    quantity: 1,
    price: 209.99,
    category: "Shoes",
  },
  {
    title: "Cowboy boots",
    id: 77,
    image: "s17.jpg",
    quantity: 1,
    price: 219.99,
    category: "Shoes",
  },
  {
    title: "Loffers",
    id: 78,
    image: "s18.jpg",
    quantity: 1,
    price: 229.99,
    category: "Shoes",
  },
  {
    title: "Silverblack Sneakers",
    id: 79,
    image: "s19.jpg",
    quantity: 1,
    price: 239.99,
    category: "Shoes",
  },
  {
    title: "Nike red running shoe",
    id: 80,
    image: "s20.jpg",
    quantity: 1,
    price: 249.99,
    category: "Shoes",
  },
  {
    title: "Casual Tote Bag",
    id: 81,
    image: "b1.jpg",
    quantity: 1,
    price: 39.99,
    category: "Bags",
  },
  {
    title: "Elegant Clutch",
    id: 82,
    image: "b2.jpg",
    quantity: 1,
    price: 49.99,
    category: "Bags",
  },
  {
    title: "Functional Backpack",
    id: 83,
    image: "b3.jpg",
    quantity: 1,
    price: 59.99,
    category: "Bags",
  },
  {
    title: "Casual Crossbody Bag",
    id: 84,
    image: "b4.jpg",
    quantity: 1,
    price: 69.99,
    category: "Bags",
  },
  {
    title: "Elegant Beaded Clutch",
    id: 85,
    image: "b5.jpg",
    quantity: 1,
    price: 79.99,
    category: "Bags",
  },
  {
    title: "Functional Bag",
    id: 86,
    image: "b6.jpg",
    quantity: 1,
    price: 89.99,
    category: "Bags",
  },
  {
    title: "Casual Messenger Bag",
    id: 87,
    image: "b7.jpg",
    quantity: 1,
    price: 99.99,
    category: "Bags",
  },
  {
    title: "Elegant Leather Bag",
    id: 88,
    image: "b8.jpg",
    quantity: 1,
    price: 109.99,
    category: "Bags",
  },
  {
    title: "Functional date Bag",
    id: 89,
    image: "b9.jpg",
    quantity: 1,
    price: 119.99,
    category: "Bags",
  },
  {
    title: "Casual Shoulder Bag",
    id: 90,
    image: "b10.jpg",
    quantity: 1,
    price: 129.99,
    category: "Bags",
  },
  {
    title: "Elegant black bag",
    id: 91,
    image: "b11.jpg",
    quantity: 1,
    price: 139.99,
    category: "Bags",
  },
  {
    title: "veggy Bag",
    id: 92,
    image: "b12.jpg",
    quantity: 1,
    price: 149.99,
    category: "Bags",
  },
  {
    title: "Casual Fanny Pack",
    id: 93,
    image: "b13.jpg",
    quantity: 1,
    price: 159.99,
    category: "Bags",
  },
  {
    title: "Elegant Leather Clutch",
    id: 94,
    image: "b14.jpg",
    quantity: 1,
    price: 169.99,
    category: "Bags",
  },
  {
    title: "Functional gucci Carrier",
    id: 95,
    image: "b15.jpg",
    quantity: 1,
    price: 179.99,
    category: "Bags",
  },
  {
    title: "Casual Bag",
    id: 96,
    image: "b16.jpg",
    quantity: 1,
    price: 189.99,
    category: "Bags",
  },
  {
    title: "Elegant Beaded Clutch",
    id: 97,
    image: "b17.jpg",
    quantity: 1,
    price: 199.99,
    category: "Bags",
  },
  {
    title: "Functional outside Bag",
    id: 98,
    image: "b18.jpg",
    quantity: 1,
    price: 209.99,
    category: "Bags",
  },
  {
    title: "Casual hand Bag",
    id: 99,
    image: "b19.jpg",
    quantity: 1,
    price: 219.99,
    category: "Bags",
  },
  {
    title: "Elegant Leather Bag",
    id: 100,
    image: "b20.jpg",
    quantity: 1,
    price: 229.99,
    category: "Bags",
  }
];

export default CartData
