const CartData = [
  {
    title: "Casual T-Shirt",
    id: 1,
    image: "c1.jpg",
    quantity: 1,
    price: 19.99,
    category: "Casual",
  },
  {
    title: "Denim Jeans",
    id: 2,
    image: "c2.jpg",
    quantity: 1,
    price: 29.99,
    category: "Casual",
  },
  {
    title: "Hooded Sweatshirt",
    id: 3,
    image: "c3.jpg",
    quantity: 1,
    price: 39.99,
    category: "Casual",
  },
  {
    title: "Plaid Shirt",
    id: 4,
    image: "c4.jpg",
    quantity: 1,
    price: 24.99,
    category: "Casual",
  },
  {
    title: "Chino Pants",
    id: 5,
    image: "c5.jpg",
    quantity: 1,
    price: 34.99,
    category: "Casual",
  },
  {
    title: "Polo Shirt",
    id: 6,
    image: "c6.jpg",
    quantity: 1,
    price: 22.99,
    category: "Casual",
  },
  {
    title: "Cargo Shorts",
    id: 7,
    image: "c7.jpg",
    quantity: 1,
    price: 27.99,
    category: "Casual",
  },
  {
    title: "Casual Blazer",
    id: 8,
    image: "c8.jpg",
    quantity: 1,
    price: 49.99,
    category: "Casual",
  },
  {
    title: "Casual Dress",
    id: 9,
    image: "c9.jpg",
    quantity: 1,
    price: 39.99,
    category: "Casual",
  },
  {
    title: "Striped Sweater",
    id: 10,
    image: "c10.jpg",
    quantity: 1,
    price: 29.99,
    category: "Casual",
  },
  {
    title: "Casual Skirt",
    id: 11,
    image: "c11.jpg",
    quantity: 1,
    price: 26.99,
    category: "Casual",
  },
  {
    title: "Linen Shirt",
    id: 12,
    image: "c12.jpg",
    quantity: 1,
    price: 32.99,
    category: "Casual",
  },
  {
    title: "Printed T-Shirt",
    id: 13,
    image: "c13.jpg",
    quantity: 1,
    price: 21.99,
    category: "Casual",
  },
  {
    title: "Casual Jumpsuit",
    id: 14,
    image: "c14.jpg",
    quantity: 1,
    price: 44.99,
    category: "Casual",
  },
  {
    title: "Canvas Sneakers",
    id: 15,
    image: "c15.jpg",
    quantity: 1,
    price: 37.99,
    category: "Casual",
  },
  {
    title: "Cropped Jeans",
    id: 16,
    image: "c16.jpg",
    quantity: 1,
    price: 31.99,
    category: "Casual",
  },
  {
    title: "Casual Cardigan",
    id: 17,
    image: "c17.jpg",
    quantity: 1,
    price: 28.99,
    category: "Casual",
  },
  {
    title: "Athleisure Leggings",
    id: 18,
    image: "c18.jpg",
    quantity: 1,
    price: 23.99,
    category: "Casual",
  },
  {
    title: "Knit Pullover",
    id: 19,
    image: "c19.jpg",
    quantity: 1,
    price: 36.99,
    category: "Casual",
  },
  {
    title: "Casual Romper",
    id: 20,
    image: "c20.jpg",
    quantity: 1,
    price: 41.99,
    category: "Casual",
  },
  {
    title: "Elegant Evening Gown",
    id: 21,
    image: "e1.jpg",
    quantity: 1,
    price: 79.99,
    category: "Elegant",
  },
  {
    title: "Elegant Blazer",
    id: 22,
    image: "e2.jpg",
    quantity: 1,
    price: 89.99,
    category: "Elegant",
  },
  {
    title: "Elegant Tuxedo",
    id: 23,
    image: "e3.jpg",
    quantity: 1,
    price: 129.99,
    category: "Elegant",
  },
  {
    title: "Elegant Wedding Dress",
    id: 24,
    image: "e4.jpg",
    quantity: 1,
    price: 159.99,
    category: "Elegant",
  },
  {
    title: "Elegant Suit",
    id: 25,
    image: "e5.jpg",
    quantity: 1,
    price: 119.99,
    category: "Elegant",
  },
  {
    title: "Elegant Evening Jacket",
    id: 26,
    image: "e6.jpg",
    quantity: 1,
    price: 99.99,
    category: "Elegant",
  },
  {
    title: "Elegant Cocktail Dress",
    id: 27,
    image: "e7.jpg",
    quantity: 1,
    price: 109.99,
    category: "Elegant",
  },
  {
    title: "Elegant Tailored Pants",
    id: 28,
    image: "e8.jpg",
    quantity: 1,
    price: 139.99,
    category: "Elegant",
  },
  {
    title: "Elegant Leather Jacket",
    id: 29,
    image: "e9.jpg",
    quantity: 1,
    price: 149.99,
    category: "Elegant",
  },
  {
    title: "Elegant Silk Blouse",
    id: 30,
    image: "e10.jpg",
    quantity: 1,
    price: 99.99,
    category: "Elegant",
  },
  {
    title: "Elegant Leather Skirt",
    id: 31,
    image: "e11.jpg",
    quantity: 1,
    price: 119.99,
    category: "Elegant",
  },
  {
    title: "Elegant Trench Coat",
    id: 32,
    image: "e12.jpg",
    quantity: 1,
    price: 129.99,
    category: "Elegant",
  },
  {
    title: "Elegant Woolen Sweater",
    id: 33,
    image: "e13.jpg",
    quantity: 1,
    price: 89.99,
    category: "Elegant",
  },
  {
    title: "Elegant Leather Boots",
    id: 34,
    image: "e14.jpg",
    quantity: 1,
    price: 109.99,
    category: "Elegant",
  },
  {
    title: "Elegant Silk Scarf",
    id: 35,
    image: "e15.jpg",
    quantity: 1,
    price: 29.99,
    category: "Elegant",
  },
  {
    title: "Elegant Leather Belt",
    id: 36,
    image: "e16.jpg",
    quantity: 1,
    price: 39.99,
    category: "Elegant",
  },
  {
    title: "Elegant Pearl Necklace",
    id: 37,
    image: "e17.jpg",
    quantity: 1,
    price: 49.99,
    category: "Elegant",
  },
  {
    title: "Elegant Diamond Earrings",
    id: 38,
    image: "e18.jpg",
    quantity: 1,
    price: 59.99,
    category: "Elegant",
  },
  {
    title: "Elegant Gold Watch",
    id: 39,
    image: "e19.jpg",
    quantity: 1,
    price: 69.99,
    category: "Elegant",
  },
  {
    title: "Elegant Leather Wallet",
    id: 40,
    image: "e20.jpg",
    quantity: 1,
    price: 79.99,
    category: "Elegant",
  },
  {
    title: "Elegant Pearl Necklace",
    id: 41,
    image: "a1.jpg",
    quantity: 1,
    price: 19.99,
    category: "Accessories",
  },
  {
    title: "Casual Leather Belt",
    id: 42,
    image: "a2.jpg",
    quantity: 1,
    price: 29.99,
    category: "Accessories",
  },
  {
    title: "Elegant Diamond Earrings",
    id: 43,
    image: "a3.jpg",
    quantity: 1,
    price: 39.99,
    category: "Accessories",
  },
  {
    title: "Casual Leather Wallet",
    id: 44,
    image: "a4.jpg",
    quantity: 1,
    price: 49.99,
    category: "Accessories",
  },
  {
    title: "Elegant Gold Watch",
    id: 45,
    image: "a5.jpg",
    quantity: 1,
    price: 59.99,
    category: "Accessories",
  },
  {
    title: "Casual Leather Boots",
    id: 46,
    image: "a6.jpg",
    quantity: 1,
    price: 69.99,
    category: "Accessories",
  },
  {
    title: "Elegant Silk Scarf",
    id: 47,
    image: "a7.jpg",
    quantity: 1,
    price: 79.99,
    category: "Accessories",
  },
  {
    title: "Casual Leather Jacket",
    id: 48,
    image: "a8.jpg",
    quantity: 1,
    price: 89.99,
    category: "Accessories",
  },
  {
    title: "Elegant Pearl Bracelet",
    id: 49,
    image: "a9.jpg",
    quantity: 1,
    price: 99.99,
    category: "Accessories",
  },
  {
    title: "Casual Leather Gloves",
    id: 50,
    image: "a10.jpg",
    quantity: 1,
    price: 109.99,
    category: "Accessories",
  },
  {
    title: "Elegant Diamond Ring",
    id: 51,
    image: "a11.jpg",
    quantity: 1,
    price: 119.99,
    category: "Accessories",
  },
  {
    title: "Casual Leather Hat",
    id: 52,
    image: "a12.jpg",
    quantity: 1,
    price: 129.99,
    category: "Accessories",
  },
  {
    title: "Elegant Pearl Earrings",
    id: 53,
    image: "a13.jpg",
    quantity: 1,
    price: 139.99,
    category: "Accessories",
  },
  {
    title: "Casual Leather Backpack",
    id: 54,
    image: "a14.jpg",
    quantity: 1,
    price: 149.99,
    category: "Accessories",
  },
  {
    title: "Elegant Gold Chain",
    id: 55,
    image: "a15.jpg",
    quantity: 1,
    price: 159.99,
    category: "Accessories",
  },
  {
    title: "Casual Leather Shoes",
    id: 56,
    image: "a16.jpg",
    quantity: 1,
    price: 169.99,
    category: "Accessories",
  },
  {
    title: "Elegant Pearl Necklace",
    id: 57,
    image: "a17.jpg",
    quantity: 1,
    price: 179.99,
    category: "Accessories",
  },
  {
    title: "Casual Leather Satchel",
    id: 58,
    image: "a18.jpg",
    quantity: 1,
    price: 189.99,
    category: "Accessories",
  },
  {
    title: "Elegant Diamond Pendant",
    id: 59,
    image: "a19.jpg",
    quantity: 1,
    price: 199.99,
    category: "Accessories",
  },
  {
    title: "Casual Leather Tote",
    id: 60,
    image: "a20.jpg",
    quantity: 1,
    price: 209.99,
    category: "Accessories",
  },
  {
    title: "Casual Sneakers",
    id: 61,
    image: "s1.jpg",
    quantity: 1,
    price: 59.99,
    category: "Shoes",
  },
  {
    title: "Elegant Leather Boots",
    id: 62,
    image: "s2.jpg",
    quantity: 1,
    price: 69.99,
    category: "Shoes",
  },
  {
    title: "Sporty Running Shoes",
    id: 63,
    image: "s3.jpg",
    quantity: 1,
    price: 79.99,
    category: "Shoes",
  },
  {
    title: "Casual Sandals",
    id: 64,
    image: "s4.jpg",
    quantity: 1,
    price: 89.99,
    category: "Shoes",
  },
  {
    title: "Elegant Heels",
    id: 65,
    image: "s5.jpg",
    quantity: 1,
    price: 99.99,
    category: "Shoes",
  },
  {
    title: "Sporty Hiking Boots",
    id: 66,
    image: "s6.jpg",
    quantity: 1,
    price: 109.99,
    category: "Shoes",
  },
  {
    title: "Casual Flip Flops",
    id: 67,
    image: "s7.jpg",
    quantity: 1,
    price: 119.99,
    category: "Shoes",
  },
  {
    title: "Elegant Pumps",
    id: 68,
    image: "s8.jpg",
    quantity: 1,
    price: 129.99,
    category: "Shoes",
  },
  {
    title: "Sporty Running Sandals",
    id: 69,
    image: "s9.jpg",
    quantity: 1,
    price: 139.99,
    category: "Shoes",
  },
  {
    title: "Casual Slippers",
    id: 70,
    image: "s10.jpg",
    quantity: 1,
    price: 149.99,
    category: "Shoes",
  },
  {
    title: "Elegant Wedges",
    id: 71,
    image: "s11.jpg",
    quantity: 1,
    price: 159.99,
    category: "Shoes",
  },
  {
    title: "Sporty Snow Boots",
    id: 72,
    image: "s12.jpg",
    quantity: 1,
    price: 169.99,
    category: "Shoes",
  },
  {
    title: "Casual Moccasins",
    id: 73,
    image: "s13.jpg",
    quantity: 1,
    price: 179.99,
    category: "Shoes",
  },
  {
    title: "Elegant Flats",
    id: 74,
    image: "s14.jpg",
    quantity: 1,
    price: 189.99,
    category: "Shoes",
  },
  {
    title: "Sporty Running Shoes",
    id: 75,
    image: "s15.jpg",
    quantity: 1,
    price: 199.99,
    category: "Shoes",
  },
  {
    title: "Casual Clogs",
    id: 76,
    image: "s16.jpg",
    quantity: 1,
    price: 209.99,
    category: "Shoes",
  },
  {
    title: "Elegant High Heels",
    id: 77,
    image: "s17.jpg",
    quantity: 1,
    price: 219.99,
    category: "Shoes",
  },
  {
    title: "Sporty Hiking Boots",
    id: 78,
    image: "s18.jpg",
    quantity: 1,
    price: 229.99,
    category: "Shoes",
  },
  {
    title: "Casual Sneakers",
    id: 79,
    image: "s19.jpg",
    quantity: 1,
    price: 239.99,
    category: "Shoes",
  },
  {
    title: "Elegant Pumps",
    id: 80,
    image: "s20.jpg",
    quantity: 1,
    price: 249.99,
    category: "Shoes",
  },
  {
    title: "Casual Tote Bag",
    id: 81,
    image: "b1.jpg",
    quantity: 1,
    price: 39.99,
    category: "Bags",
  },
  {
    title: "Elegant Clutch",
    id: 82,
    image: "b2.jpg",
    quantity: 1,
    price: 49.99,
    category: "Bags",
  },
  {
    title: "Functional Backpack",
    id: 83,
    image: "b3.jpg",
    quantity: 1,
    price: 59.99,
    category: "Bags",
  },
  {
    title: "Casual Crossbody Bag",
    id: 84,
    image: "b4.jpg",
    quantity: 1,
    price: 69.99,
    category: "Bags",
  },
  {
    title: "Elegant Beaded Clutch",
    id: 85,
    image: "b5.jpg",
    quantity: 1,
    price: 79.99,
    category: "Bags",
  },
  {
    title: "Functional Laptop Bag",
    id: 86,
    image: "b6.jpg",
    quantity: 1,
    price: 89.99,
    category: "Bags",
  },
  {
    title: "Casual Messenger Bag",
    id: 87,
    image: "b7.jpg",
    quantity: 1,
    price: 99.99,
    category: "Bags",
  },
  {
    title: "Elegant Leather Bag",
    id: 88,
    image: "b8.jpg",
    quantity: 1,
    price: 109.99,
    category: "Bags",
  },
  {
    title: "Functional Gym Bag",
    id: 89,
    image: "b9.jpg",
    quantity: 1,
    price: 119.99,
    category: "Bags",
  },
  {
    title: "Casual Shoulder Bag",
    id: 90,
    image: "b10.jpg",
    quantity: 1,
    price: 129.99,
    category: "Bags",
  },
  {
    title: "Elegant Beaded Tote",
    id: 91,
    image: "b11.jpg",
    quantity: 1,
    price: 139.99,
    category: "Bags",
  },
  {
    title: "Functional Travel Bag",
    id: 92,
    image: "b12.jpg",
    quantity: 1,
    price: 149.99,
    category: "Bags",
  },
  {
    title: "Casual Fanny Pack",
    id: 93,
    image: "b13.jpg",
    quantity: 1,
    price: 159.99,
    category: "Bags",
  },
  {
    title: "Elegant Leather Clutch",
    id: 94,
    image: "b14.jpg",
    quantity: 1,
    price: 169.99,
    category: "Bags",
  },
  {
    title: "Functional Baby Carrier",
    id: 95,
    image: "b15.jpg",
    quantity: 1,
    price: 179.99,
    category: "Bags",
  },
  {
    title: "Casual Shopping Bag",
    id: 96,
    image: "b16.jpg",
    quantity: 1,
    price: 189.99,
    category: "Bags",
  },
  {
    title: "Elegant Beaded Clutch",
    id: 97,
    image: "b17.jpg",
    quantity: 1,
    price: 199.99,
    category: "Bags",
  },
  {
    title: "Functional Laptop Bag",
    id: 98,
    image: "b18.jpg",
    quantity: 1,
    price: 209.99,
    category: "Bags",
  },
  {
    title: "Casual Messenger Bag",
    id: 99,
    image: "b19.jpg",
    quantity: 1,
    price: 219.99,
    category: "Bags",
  },
  {
    title: "Elegant Leather Bag",
    id: 100,
    image: "b20.jpg",
    quantity: 1,
    price: 229.99,
    category: "Bags",
  },
  {
    title: "Casual Lipstick",
    id: 101,
    image: "be1.jpg",
    quantity: 1,
    price: 19.99,
    category: "Makeup",
  },
  {
    title: "Elegant Eye Shadow",
    id: 102,
    image: "be2.jpg",
    quantity: 1,
    price: 29.99,
    category: "Makeup",
  },
  {
    title: "Professional Foundation",
    id: 103,
    image: "be3.jpg",
    quantity: 1,
    price: 39.99,
    category: "Makeup",
  },
  {
    title: "Casual Blush",
    id: 104,
    image: "be4.jpg",
    quantity: 1,
    price: 49.99,
    category: "Makeup",
  },
  {
    title: "Elegant Eyeliner",
    id: 105,
    image: "be5.jpg",
    quantity: 1,
    price: 59.99,
    category: "Makeup",
  },
  {
    title: "Professional Highlighter",
    id: 106,
    image: "be6.jpg",
    quantity: 1,
    price: 69.99,
    category: "Makeup",
  },
  {
    title: "Casual Mascara",
    id: 107,
    image: "be7.jpg",
    quantity: 1,
    price: 79.99,
    category: "Makeup",
  },
  {
    title: "Elegant Nail Polish",
    id: 108,
    image: "be8.jpg",
    quantity: 1,
    price: 89.99,
    category: "Makeup",
  },
  {
    title: "Professional Concealer",
    id: 109,
    image: "be9.jpg",
    quantity: 1,
    price: 99.99,
    category: "Makeup",
  },
  {
    title: "Casual Eye Cream",
    id: 110,
    image: "be10.jpg",
    quantity: 1,
    price: 109.99,
    category: "Makeup",
  },
  {
    title: "Elegant Lip Gloss",
    id: 111,
    image: "be11.jpg",
    quantity: 1,
    price: 119.99,
    category: "Makeup",
  },
  {
    title: "Professional Primer",
    id: 112,
    image: "be12.jpg",
    quantity: 1,
    price: 129.99,
    category: "Makeup",
  },
  {
    title: "Casual Eye Shadow Palette",
    id: 113,
    image: "be13.jpg",
    quantity: 1,
    price: 139.99,
    category: "Makeup",
  },
  {
    title: "Elegant Nail Polish Set",
    id: 114,
    image: "be14.jpg",
    quantity: 1,
    price: 149.99,
    category: "Makeup",
  },
  {
    title: "Professional Makeup Remover",
    id: 115,
    image: "be15.jpg",
    quantity: 1,
    price: 159.99,
    category: "Makeup",
  },
  {
    title: "Casual Lip Liner",
    id: 116,
    image: "be16.jpg",
    quantity: 1,
    price: 169.99,
    category: "Makeup",
  },
  {
    title: "Elegant Eye Liner",
    id: 117,
    image: "be17.jpg",
    quantity: 1,
    price: 179.99,
    category: "Makeup",
  },
  {
    title: "Professional Eye Cream",
    id: 118,
    image: "be18.jpg",
    quantity: 1,
    price: 189.99,
    category: "Makeup",
  },
  {
    title: "Casual Blush Palette",
    id: 119,
    image: "be19.jpg",
    quantity: 1,
    price: 199.99,
    category: "Makeup",
  },
  {
    title: "Elegant Lip Gloss Set",
    id: 120,
    image: "be20.jpg",
    quantity: 1,
    price: 209.99,
    category: "Makeup",
  }
];
